version: 2
updates:
  - package-ecosystem: github-actions
    cooldown:
      default-days: 7
    directories:
      - "/"
    schedule:
      interval: weekly
    groups:
      minor-and-patch:
        patterns: ["*"]
        update-types: [minor, patch]
    open-pull-requests-limit: 1000
  - package-ecosystem: docker
    directories:
      - "/.github/workflows"
    schedule:
      interval: weekly
    cooldown:
      default-days: 7
