#!/usr/bin/env python3
"""Generate docs/SKILL-CATALOG.md (full skill catalog)."""

from __future__ import annotations

from pathlib import Path

REPO = Path(__file__).resolve().parents[1]
OUT = REPO / "docs" / "SKILL-CATALOG.md"
GITHUB = "https://github.com/PrunaAI/pruna-skills/tree/main"


def read_frontmatter(skill_md: Path) -> dict[str, str]:
    text = skill_md.read_text()
    if not text.startswith("---"):
        return {}
    block = text.split("---", 2)[1]
    out: dict[str, str] = {}
    for line in block.splitlines():
        if ":" in line and not line.startswith(" "):
            k, v = line.split(":", 1)
            out[k.strip()] = v.strip().strip('"')
    return out


def collect(base: Path) -> list[tuple[str, str, str]]:
    rows: list[tuple[str, str, str]] = []
    if not base.is_dir():
        return rows
    for skill_md in sorted(base.rglob("SKILL.md")):
        fm = read_frontmatter(skill_md)
        name = fm.get("name") or skill_md.parent.name
        desc = fm.get("description", "")
        desc = desc.replace("|", "\\|")
        rel = skill_md.parent.relative_to(REPO).as_posix()
        rows.append((name, desc, f"{GITHUB}/{rel}/SKILL.md"))
    return rows


def table(title: str, rows: list[tuple[str, str, str]]) -> str:
    if not rows:
        return ""
    lines = [f"### {title}", "", "| Skill | Description |", "|-------|-------------|"]
    for name, desc, link in rows:
        lines.append(f"| [{name}]({link}) | {desc} |")
    lines.append("")
    return "\n".join(lines)


def build_body() -> str:
    guides = collect(REPO / "skills" / "guides")
    tools_image = collect(REPO / "skills" / "image")
    tools_video = collect(REPO / "skills" / "video")
    tools_audio = collect(REPO / "skills" / "audio")
    workflows = collect(REPO / "skills" / "workflows")
    suite = collect(REPO / "skills" / "suite")

    return "\n".join(
        [
            "<!-- generated by .maintainer/write_readme_skills_section.py; do not edit -->",
            "",
            "# Pruna Skills — full catalog",
            "",
            "Browse by type. Default install: **`/pruna`** — see [README Quickstart](../README.md#quickstart). Per-skill commands: [skills/suite/pruna/SKILL.md](../skills/suite/pruna/SKILL.md).",
            "",
            "## Available Skills",
            "",
            table("Suite", suite),
            table("Guides (vendor-neutral craft)", guides),
            table("Tools — image (Pruna API)", tools_image),
            table("Tools — video (Pruna API)", tools_video),
            table("Tools — audio (Replicate)", tools_audio),
            table("Workflows", workflows),
        ]
    ).rstrip() + "\n"


def main() -> None:
    body = build_body()
    OUT.write_text(body)
    print(f"wrote {OUT.relative_to(REPO)}")


if __name__ == "__main__":
    main()
