#!/usr/bin/env python3
"""Generate README.skills.md — Available Skills tables from source tree."""

from __future__ import annotations

import re
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]
OUT = REPO / "README.skills.md"
GITHUB = "https://github.com/PrunaAI/pruna-skills/tree/main"


def read_frontmatter(skill_md: Path) -> dict[str, str]:
    text = skill_md.read_text()
    if not text.startswith("---"):
        return {}
    block = text.split("---", 2)[1]
    out: dict[str, str] = {}
    for line in block.splitlines():
        if ":" in line and not line.startswith(" "):
            k, v = line.split(":", 1)
            out[k.strip()] = v.strip().strip('"')
    return out


def collect(base: Path) -> list[tuple[str, str, str]]:
    rows: list[tuple[str, str, str]] = []
    if not base.is_dir():
        return rows
    for skill_md in sorted(base.rglob("SKILL.md")):
        fm = read_frontmatter(skill_md)
        name = fm.get("name") or skill_md.parent.name
        desc = fm.get("description", "")
        if len(desc) > 120:
            desc = desc[:117] + "…"
        rel = skill_md.parent.relative_to(REPO).as_posix()
        rows.append((name, desc, f"{GITHUB}/{rel}/SKILL.md"))
    return rows


def table(title: str, rows: list[tuple[str, str, str]]) -> str:
    if not rows:
        return ""
    lines = [f"### {title}", "", "| Skill | Description |", "|-------|-------------|"]
    for name, desc, link in rows:
        lines.append(f"| [{name}]({link}) | {desc} |")
    lines.append("")
    return "\n".join(lines)


def main() -> None:
    tools_image = collect(REPO / "tools" / "image")
    tools_video = collect(REPO / "tools" / "video")
    tools_audio = collect(REPO / "tools" / "audio")
    guides = collect(REPO / "guides")
    router = collect(REPO / "workflows" / "router")
    core = collect(REPO / "workflows" / "core")
    verticals = collect(REPO / "workflows" / "verticals")

    body = "\n".join(
        [
            "<!-- generated by scripts/write_readme_skills_section.py; do not edit -->",
            "",
            "## Available Skills",
            "",
            table("Tools — image (Pruna API)", tools_image),
            table("Tools — video (Pruna API)", tools_video),
            table("Tools — audio (Replicate)", tools_audio),
            table("Guides — prompting, quality, routing", guides),
            table("Workflows — router", router),
            table("Workflows — core", core),
            table("Workflows — verticals", verticals),
        ]
    )
    OUT.write_text(body.rstrip() + "\n")
    print(f"wrote {OUT.relative_to(REPO)}")


if __name__ == "__main__":
    main()
